create channels list and track page :rocket:
ehsaantech/ehsaan-stream-web pull request #1
Opened 2022-10-12 15:00 UTC by Tanzeel-khan

2022-10-19 07:31 UTC, ecspress requested changes

2022-10-19 07:31 UTC, ecspress commented on package.json
>      "@testing-library/jest-dom": "^5.16.5",
dev dependencies (testing, types, ts) should not be listed in dependencies

2022-10-19 07:31 UTC, ecspress commented on package.json
>      "@mui/material": "^5.10.8",
why do we need emotion/* and styledcomponents both?

2022-10-19 07:31 UTC, ecspress commented on package.json
>      "@mui/material": "^5.10.8",
if we are going to use 3rd party ui library, then all components need to be wrapped.

2022-10-19 07:31 UTC, ecspress commented on src/App.tsx
> +        <Route path = "/channels/:channelName" element={<Tracks/>}/>
routes need to be in their own file.

2022-10-19 07:31 UTC, ecspress commented on src/components/Channels/index.tsx
> +import { mobile } from '../../utils/responsive';
setup project to avoid using relative imports '../../../'

2022-10-19 07:31 UTC, ecspress commented on src/components/Channels/index.tsx
> +  z-index: 3;
fix formatter in ide to autoformat

2022-10-19 07:31 UTC, ecspress commented on src/components/Channels/index.tsx
> +    color:white;
move theme related info to theme file (colors, font, ...)

2022-10-19 07:31 UTC, ecspress commented on src/components/Channels/index.tsx
> +}
dont navigate from component

2022-10-19 07:31 UTC, ecspress commented on src/components/Channels/index.tsx
> +    </>
dont use fragment for only one child

2022-10-19 11:43 UTC, aitchkhan commented on .firebase/hosting.YnVpbGQ.cache
> +asset-manifest.json,1665773265084,c23a589488f08c6caa05c63a6c216cfc494831f60a4cde9d81c93c5120e8db54
add .firebase to .gitignore and remove it from commit

2023-01-24 16:25 UTC, ecspress reviewed
Add prettier formatter to format code.

2023-01-24 16:25 UTC, ecspress commented on src/components/Footer/index.tsx
> +`;
merge these styles

2023-01-24 16:25 UTC, ecspress commented on src/components/Hero/index.tsx
> +    </>
use a string file for text strings

2023-01-24 16:25 UTC, ecspress commented on src/types/tracks.ts
> +    channelTracks: any;
dont use any

2023-01-24 16:25 UTC, ecspress commented on src/container/tracks-container.tsx
> +        <Card sx={{ display: "flex", maxWidth: "800px" }}>
no inline styles if we are using styled-components

2023-01-24 16:25 UTC, ecspress commented on src/routes.tsx
> +  const channelImg = channelData[channelIndex]?.img;
can we use destructuring here?

2023-03-21 04:41 UTC, merged